### PR TITLE
rails 4 compatibility

### PR DESCRIPTION
**Pull request by foodforarabbit**
Never mind all the commits the logs weren't showing up properly in my terminal but I figured out it was a problem on my end. This works with rails4 and should work with rails3.

### CODE REVIEW

**Comment by pauldowman** [comment]
Thanks! I won't have a chance to check it out in the next few days but I'll try to review and merge it next week.

**Comment by nateware** [comment]
Hi, just checking in on Rails 4 compat... would love to keep using better_logging, it's a great gem

**Comment by misham** [comment]
+1

**Comment by pauldowman** [comment]
Hey guys thanks for this and I'm sorry for the lack of response. I've actually stopped using this myself and am too busy to maintain it. Would one of you like to?

**Comment by foodforarabbit** [comment]
Hey Paul, I've stopped using this as well but I can take over if no one else wants to. I have a bit of spare time and I've always wanted to contribute something.. I guess this is as good a time to start as ever. Let me know what I have to do as a maintainer.

**Comment by pauldowman** [comment]
Thanks @foodforarabbit. Well in order for me to not be a bottleneck I'll point everyone to your fork (I'll update the README), and I'll need to set you as the owner of the gem. What's your rubygems user id?

**Comment by foodforarabbit** [comment]
My user id is rabbitfood

**Comment by pauldowman** [comment]
@foodforarabbit I updated the README to point to your fork: https://github.com/pauldowman/better_logging/commit/85e4cd0e19dc8f521d4ce32aa38bd15328c58484

**Pull request closed without merging**
